### ISSUE TITLE
Add new contributors to repository

### ISSUE THREAD

**Issue by agmcarthur** [arpcard/mobio#12]
- [x] Emma Griffiths @griffie
- [x] William Hsiao @wwhsiao
- [x] Nicole Ricker @rickernic
- [x] Emily Bordeleau @emilyann-RB
- [x] Brian Alcock @bpalcock
- [x] Daniel Gyamfi Amoako @DanielGyamfiAmoako

**Comment by agmcarthur** [comment]
@raphenya @arpcard  could you add the above as contributors to this repo.

**Comment by arpcard** [comment]
@bpalcock you have a pending invite.
